### ISSUE TITLE
Incorrect graph

### ISSUE THREAD

**Issue by vovak** [nmramorov/JB_test#1]
Hi, here is what the graph looks like for me.
![image](https://user-images.githubusercontent.com/1163206/95355365-c44ea500-08c5-11eb-9c6c-8a51b76000a1.png)

Is there anything I should do to fix it?

**Comment by nmramorov** [comment]
Nope, unfortunately. The thing is - I didn't manage to get useful
information from Github using it's API. Another thing is that to complete
this assignment by any chance, I tried to create some graph, which would
show something meaningful. That's where I made another mistake.
Sorry if I wasted your time but that thing is the only one I managed to
complete.

ср, 7 окт. 2020 г. в 20:52, Vladimir Kovalenko <notifications@github.com>:

**Comment by vovak** [comment]
Thank you for swift reaction.
